### ISSUE TITLE
Discussion on strategies

### ISSUE THREAD

**Issue by storm255** [bjunc/access-decision-manager#1]
Hi.  Great to see this type of authorisation being worked on for Elixir.

I noticed that you were looking at discussing different implementations of strategies.  Is that taking place on github, or somewhere else?  What sort of input/discussion are you looking for?

I would like to help if I can and am interested in the :strategy_unanimous particularly, in something I am working on now.

Thanks again and good work. 

Mark.

**Comment by bjunc** [comment]
Hi Mark,

Here is fine for discussion, I suppose.  I guess if it gets lively, we can use a chat (Slack, Skype, etc.).

Glad you find this module useful.  It shouldn't be difficult to implement `:strategy_unanimous`.  I already have the basic bones in place via the first param of the `decide()` private function pattern matching the access decision strategy.

Per Symfony's way of doing it, the decision strategy is set at the config level, which would make it apply for all `granted?()` calls.  Even though I'm largely basing my code on how Symfony does it, I was a little hesitant to have the same strategy apply for _all_ calls.  Would it work for you if the strategy was set at the config level, and all `granted?()` calls used the same strategy?  If so, I can implement that pretty quickly.  It'd look something like this:

```elixir
# config.exs
config :access_decision_manager,
  voters: [MyApp.Auth.FooVoter],
  strategy: :strategy_unanimous,
  allow_if_all_abstain: false
```

> For `:strategy_unanimous`, if all voters abstained from voting, the decision is based on the `allow_if_all_abstain` config option.

Here's a quick reference from Symfony's docs: [How to Use Voters to Check User Permissions](https://symfony.com/doc/current/security/voters.html)

**Comment by storm255** [comment]
Thanks for the additional information Bobby.  It helped solidify the concepts in my mind.
I think I can make it work with :strategy_unanimous either at the config level or per call.  

Really I think I would just have to be careful as the application grows to manage the authorisation hierarchy in a concise way that avoids conflicting votes as much as possible, so it is both understandable and avoids authorisation side effects.

The ideal I am looking at implementing is to give coarse control to larger parts of the application, yet still restrict individual actions with an opposing rule if needed.  I would guess that the :strategy_unanimous would apply here with a both a role vote and an individual vote being required in critical functions, and possibly a looser interpretation (like :strategy_concensus) for less strict options.

Perhaps the fallback would be to use the configured strategy unless an optional strategy is passed in.

Thanks again.

**Comment by bjunc** [comment]
I pushed an update (`v0.3.0`) which adds support for `:strategy_unanimous`.  When set (via config), the strategy applies for _all_ voters.  Give it a whirl, and let me know what you think. I also added more docs (both in the readme and in hex).

Your use-case for unanimous seems to make sense, but I find myself almost always using `:strategy_affirmative`.  One example for unanimous would be where one voter checks if the user is authenticated, and other checks to see if they're over 18.  Even then though, you could simply do two separate calls with `:strategy_affirmative` (eg. `granted?(user, "ROLE_AUTHENTICATED") && granted?(user, "ROLE_OVER_18"`).

Anyway, now you have the option to try both and see which works for you.
